window.STATE =
{
  "slug": "tg-lead-catcher",
  "dir": "2026-08-28-tg-lead-catcher--wip",
  "title": "Telegram-лидогенератор по ключевым словам",
  "mode": "semi",
  "depth": "strict",
  "polish": {
    "reference": "reference.md",
    "startedAt": "2026-08-29T05:25:00+03:00",
    "baseCommit": "73b6352",
    "rounds": [
      { "n": 1, "found": 5, "accepted": 5, "tickets": ["P1"], "finishedAt": "2026-08-29T06:10:00+03:00" },
      { "n": 2, "found": 4, "accepted": 3, "tickets": ["P2"], "finishedAt": "2026-08-29T06:55:00+03:00",
        "dropped": "format_liveness всё ещё упоминает вторую (panel) сессию сверх дословной цитаты брифа — оставлено намеренно ещё в круге 1: реальная архитектура (два Telethon-входа), не выдумка, дословный эталон этого не предвидел" },
      { "n": 3, "found": 8, "accepted": 5, "tickets": ["P3"], "finishedAt": "2026-08-29T08:15:00+03:00",
        "dropped": "3 находки (разные глаголы «работает»/«запущен», позиция ✅, недостающая подсказка «Попробуйте ещё раз» в одном из путей) — чистая стилевая консистентность, не привязаны к цитате эталона или требованию манифеста, идея критика о единообразии, не различие с эталоном" }
    ],
    "maxRounds": 3,
    "stoppedBy": "ceiling"
  },
  "tier": "T2",
  "briefFile": "2026-08-28-brief.md",
  "memoryFile": "CLAUDE.md",
  "skillDir": "/c/Users/X79/leed/.agents/skills/autopilot",
  "startedAt": "2026-08-28T18:51:58+03:00",
  "updatedAt": "2026-09-02T18:14:20+03:00",
  "finishedAt": null,
  "reopenedAt": "2026-09-02T17:40:00+03:00",
  "stages": [
    { "id": "preflight", "status": "done", "startedAt": "2026-09-02T17:40:00+03:00", "finishedAt": "2026-09-02T17:42:00+03:00", "note": "прогон переоткрыт (--wip вернулся) — найден баг после сдачи" },
    { "id": "manifest",  "status": "done", "startedAt": "2026-09-02T17:42:00+03:00", "finishedAt": "2026-09-02T17:48:00+03:00", "note": "G01/G02 добавлены" },
    { "id": "briefing",  "status": "done", "startedAt": "2026-09-02T17:48:00+03:00", "finishedAt": "2026-09-02T17:52:00+03:00", "note": "3 уточняющих вопроса — объём фикса" },
    { "id": "spec",      "status": "done", "startedAt": "2026-09-02T17:52:00+03:00", "finishedAt": "2026-09-02T18:05:00+03:00", "note": "§11 добавлен" },
    { "id": "plan",      "status": "done", "startedAt": "2026-09-02T18:05:00+03:00", "finishedAt": "2026-09-02T18:10:00+03:00", "note": "1 таск (11), волна 7" },
    { "id": "build",     "status": "active", "startedAt": "2026-09-02T18:14:20+03:00" },
    { "id": "review",    "status": "pending" },
    { "id": "final",     "status": "pending" }
  ],
  "requirements": {
    "total": 85, "done": 75, "inTicket": 2, "inSpec": 0,
    "placeholder": 0, "deferred": 8, "dropped": 0, "ticketCount": 10
  },
  "tickets": [
    { "id": "01", "title": "Ядро: схема данных и матчинг ключевых слов",
      "requirements": ["R09","R10","R13","R14","R15","R17","R18","R19","R19.1","R20","R21","R25.1","R32","R33","R60","R66","R67"],
      "blockedBy": [], "wave": 1, "zone": ["matcher/","store/",".env.example",".gitignore"], "status": "done",
      "startedAt": "2026-08-28T19:58:00+03:00", "finishedAt": "2026-08-28T21:35:00+03:00",
      "tests": "python -m pytest tests/matcher tests/store -> 20 passed", "commit": "5af0670",
      "retries": 0, "repairs": 2, "handoffs": 0 },
    { "id": "02", "title": "Userbot: приём сообщений, матчинг, дедуп, догон",
      "requirements": ["R01","R05","R06","R08","R16","R22","R23","R24","R25","R26","R34","R35","R36","R37","R54","R76i","R78i"],
      "blockedBy": ["01"], "wave": 2, "zone": ["userbot/listener.py","userbot/dialogs.py","userbot/catchup.py","userbot/client.py"], "status": "done",
      "startedAt": "2026-08-28T20:12:00+03:00", "finishedAt": "2026-08-29T00:05:00+03:00",
      "tests": "python -m pytest tests/userbot --ignore=tests/userbot/test_deliver.py -> 16 passed", "commit": "1323478",
      "retries": 0, "repairs": 1, "handoffs": 0 },
    { "id": "03", "title": "Доставка и устойчивость",
      "requirements": ["R01","R05","R08","R27","R28","R29","R30","R31","R43","R61","R62","R63","R64","R68"],
      "blockedBy": ["01"], "wave": 2, "zone": ["worker/","userbot/deliver.py"], "status": "done",
      "startedAt": "2026-08-28T20:12:00+03:00", "finishedAt": "2026-08-28T21:40:00+03:00",
      "tests": "python -m pytest tests/userbot/test_deliver.py tests/worker/ -> 13 passed", "commit": "3a207e1",
      "retries": 0, "repairs": 1, "handoffs": 0 },
    { "id": "06", "title": "Мастер настройки и автозапуск",
      "requirements": ["R11","R56","R56.1","R57","R58","R59","R65"],
      "blockedBy": ["01"], "wave": 2, "zone": ["setup.py","docker-compose.yml","Dockerfile","deploy/"], "status": "done",
      "startedAt": "2026-08-28T20:12:00+03:00", "finishedAt": "2026-08-28T21:05:00+03:00",
      "tests": "python -m pytest tests/test_setup.py -> 19 passed", "commit": "33fddf4",
      "retries": 0, "repairs": 1, "handoffs": 0 },
    { "id": "04", "title": "Панель: каркас, доступ, источники и приёмники",
      "requirements": ["R02","R03","R07","R38","R39","R40","R40.1","R41","R42","R48","R59","R79i"],
      "blockedBy": ["01","02"], "wave": 3, "zone": ["panel/__init__.py","panel/auth.py","panel/sources.py","panel/receivers.py","panel/keyboards.py"], "status": "done",
      "startedAt": "2026-08-28T21:45:00+03:00", "finishedAt": "2026-08-29T01:10:00+03:00",
      "tests": "python -m pytest tests/panel/ -> 39 passed", "commit": "91ea4b0",
      "retries": 0, "repairs": 3, "handoffs": 0 },
    { "id": "05", "title": "Панель: ключевые слова, проверка, статус, статистика, история, экспорт",
      "requirements": ["R04","R44","R45","R46","R47","R49","R50","R51","R52","R53","R55","R79i"],
      "blockedBy": ["04"], "wave": 4, "zone": ["panel/keywords.py","panel/stats.py","panel/export.py"], "status": "done",
      "startedAt": "2026-08-29T01:12:00+03:00", "finishedAt": "2026-08-29T02:10:00+03:00",
      "tests": "python -m pytest tests/panel/ -> 65 passed", "commit": "23fbda5",
      "retries": 0, "repairs": 2, "handoffs": 0 },
    { "id": "07", "title": "Точки входа: userbot/main.py, panel/main.py",
      "requirements": ["R06","R07","R11","R65"],
      "blockedBy": ["02","03","04","05","06"], "wave": 5, "zone": ["userbot/main.py","panel/main.py","docker-compose.yml(command:)","setup.py"], "status": "done",
      "startedAt": "2026-08-29T02:12:00+03:00", "finishedAt": "2026-08-29T03:40:00+03:00",
      "tests": "python -m pytest -> 144 passed", "commit": "064870c",
      "retries": 0, "repairs": 2, "handoffs": 0 },
    { "id": "09", "title": "Панель: настройки (Settings)",
      "requirements": ["R26","R31","R33","R37","R62","R68"],
      "blockedBy": ["04","05","07"], "wave": 6, "zone": ["panel/settings.py","panel/keyboards.py","panel/__init__.py"], "status": "done",
      "startedAt": "2026-08-29T04:10:00+03:00", "finishedAt": "2026-08-29T05:20:00+03:00",
      "tests": "python -m pytest tests/panel/test_settings.py -> 22 passed", "commit": "73b6352",
      "retries": 0, "repairs": 0, "handoffs": 0 },
    { "id": "10", "title": "Инфраструктура: Docker-сборка, конфликт setup.py, TZ",
      "requirements": ["R11","R14"],
      "blockedBy": ["06","07"], "wave": 6, "zone": ["Dockerfile","docker-compose.yml","setup.py","pyproject.toml","userbot/main.py","tests/test_setup.py"], "status": "done",
      "startedAt": "2026-08-29T04:10:00+03:00", "finishedAt": "2026-08-29T05:20:00+03:00",
      "tests": "docker build -> success, pip install -e -> success, python -m pytest -> 170 passed", "commit": "528f3ce",
      "retries": 0, "repairs": 1, "handoffs": 0 },
    { "id": "11", "title": "Панель: отмена и команды в FSM-вводе",
      "requirements": ["G01","G02"],
      "blockedBy": ["04","05","09"], "wave": 7, "zone": ["panel/settings.py","panel/keywords.py","panel/sources.py","panel/keyboards.py"], "status": "review",
      "startedAt": "2026-09-02T18:14:20+03:00" }
  ],
  "singlePass": null,
  "tests": null,
  "debt": { "placeholders": [], "assumptions": [], "emptyEnv": [] },
  "additions": [],
  "coverage": {
    "findings": 6,
    "missing": 2, "halfCovered": 1, "specOnly": 4,
    "resolved": "все 6 закрыты правкой spec.md: R12 (папка/git init) и .env-в-.gitignore дописаны в Решения §1/§8; TZ (R14) уточнена в Решения §2; 4 R##i (76i/78i/79i приняты с обоснованием, 77i подтверждён как Вне рамок) — добавлен раздел «Подразумеваемые требования»"
  },
  "concerns": [
    { "ticket": "01", "axis": "craft", "file": "store/repositories/sources.py:60, keywords.py:57, delivery_queue.py:53",
      "note": "динамическая сборка UPDATE повторена в трёх репозиториях — вынести общий хелпер" },
    { "ticket": "01", "axis": "craft", "file": "store/repositories/sources.py:43, receivers.py:40",
      "note": "get(id, chat_id) с идентичным ветвлением повторён — параметризовать таблицей" },
    { "ticket": "01", "axis": "craft", "file": "tests/store/",
      "note": "швы DeliveryQueueRepo/SourcesRepo/ReceiversRepo/SettingsRepo названы в interfaces.md, но без тестов — дедуп/ретеншн/очередь ничем не защищены" },
    { "ticket": "01", "axis": "manifest", "file": "matcher/ruleset.py:40-42",
      "note": "InvalidKeywordError склеивает русский префикс с сырым английским текстом re.error — весь пользовательский текст должен быть на русском (R13)" },
    { "ticket": "01", "axis": "spec", "file": "store/repositories/settings.py (add)",
      "note": "конфликт ключа даёт голый aiosqlite.IntegrityError, тогда как sources/receivers/hits заворачивают в доменную ошибку — несогласованно" },
    { "ticket": "01", "axis": "craft", "file": "store/repositories/hits.py:100-124",
      "note": "update(..., also_in=...) дублирует уже существующий update_also_in — два метода на одно поле" },
    { "ticket": "02", "axis": "craft", "file": "userbot/catchup.py:614 (INACCESSIBLE_SOURCE_ERRORS)",
      "note": "голый ValueError в кортеже без комментария — посторонний баг может тихо пометить источник paused" },
    { "ticket": "02", "axis": "craft", "file": "userbot/catchup.py:652, tests/userbot/test_catchup.py",
      "note": "предохранитель по дням (limit_days) ни разу не проверен тестом — фейковые сообщения всегда без даты" },
    { "ticket": "02", "axis": "craft", "file": "userbot/listener.py:1050-1079",
      "note": "build_incoming/_from_album_event дублируют построение IncomingMessage из sender — вынести хелпер" },
    { "ticket": "02", "axis": "craft", "file": "userbot/catchup.py",
      "note": "6 kwarg продеты через три функции подряд вместо уже существующего Deps — data clump" },
    { "ticket": "03", "axis": "craft", "file": "worker/runner.py:650-651 (monitoring_paused_reason)",
      "note": "новый settings-ключ не зарегистрирован в DEFAULT_SETTINGS/interfaces.md — невидим в settings.list() до первого падения сессии" },
    { "ticket": "03", "axis": "craft", "file": "userbot/deliver.py:430-434 (_to_internal_id)",
      "note": "ветка для обычной группы (без префикса -100) не покрыта тестом — все тесты на supergroup" },
    { "ticket": "03", "axis": "craft", "file": "worker/retention.py",
      "note": "прямой SQL в обход HitsRepo/DeliveryQueueRepo — осознанное отступление (см. тикет), формально нарушает «store прячет SQL»" },
    { "ticket": "03", "axis": "craft", "file": "worker/runner.py:106-107",
      "note": "process_pending читает BOT_TOKEN/OWNER_ID напрямую из os.environ вместо параметров — нарушает стиль DI остальной функции" },
    { "ticket": "02", "axis": "manifest", "file": "userbot/listener.py:702-705 (on_edit)",
      "note": "правка отдельного сообщения внутри уже отправленного альбома (MessageEdited с grouped_id) тихо игнорируется — Telethon не даёт события Album для правок; не покрыто тестом. R25 без исключения для альбомов" },
    { "ticket": "04", "axis": "craft", "file": "panel/sources.py (on_dialog_pick/on_manual_text/on_forward)",
      "note": "три хендлера повторяют одинаковый хвост добавления — вынести _finish_add" },
    { "ticket": "04", "axis": "craft", "file": "panel/sources.py (on_pause_toggle, on_scan_now)",
      "note": "снятие паузы/скан синхронно await-ят scan_source прямо в callback — при HARD_MSG_CAP=500 может занять минуты, блокируя панель (пережило репеат-ревью, не тронуто дозапросами)" },
    { "ticket": "04", "axis": "craft", "file": "userbot/catchup.py (INACCESSIBLE_SOURCE_ERRORS)",
      "note": "расплывчатый ValueError в кортеже (см. концерн тикета 02) — теперь панель тоже может тихо доложить постороннюю ошибку как «источник недоступен»" },
    { "ticket": "05", "axis": "craft", "file": "store/db.py DEFAULT_SETTINGS",
      "note": "monitoring_paused_at (как и monitoring_paused_reason из тикета 03) не зарегистрирован в DEFAULT_SETTINGS — второй случай той же дыры, закрыть разом на доводке" },
    { "ticket": "05", "axis": "craft", "file": "panel/stats.py to_internal_id vs userbot/deliver.py _to_internal_id",
      "note": "дословный дубль алгоритма ссылки на приватный чат — общий хелпер убрал бы дублирование" },
    { "ticket": "05", "axis": "craft", "file": "panel/keyboards.py keyword_list_kb vs list_page_kb",
      "note": "повторяет блок prev/next-навигации почти дословно" },
    { "ticket": "05", "axis": "craft", "file": "panel/sources.py + panel/stats.py (два on_toggle_monitoring)",
      "note": "два независимых хендлера на одну кнопку, порядок подключения роутеров в тикете 07 решает какой сработает — задокументировано, принято как временная мера, стоит объединить на доводке" },
    { "ticket": "05", "axis": "craft", "file": "panel/stats.py on_resume_confirm",
      "note": "литерал дефолта scan_days=\"3\" повторён в третьем месте (уже есть в DEFAULT_SETTINGS и в scan_source) — разойдётся молча при правке дефолта" },
    { "ticket": "07", "axis": "craft", "file": "userbot/main.py run() — refresh_loop/worker.run/retention.run_daily",
      "note": "три фоновые задачи запущены fire-and-forget без супервизора — необработанное исключение молча убьёт задачу навсегда без уведомления владельца, в отличие от остального проекта (\"молча стоять нельзя\")" },
    { "ticket": "09", "axis": "manifest", "file": "panel/settings.py on_settings_value",
      "note": "при ошибке валидации FSM-состояние сбрасывается (в отличие от sources.py, где остаётся для повтора) — пользователь выпадает из редактирования, а не может тут же ввести исправленное значение" },
    { "ticket": "09", "axis": "craft", "file": "panel/settings.py on_settings_toggle",
      "note": "дефолт-фолбэк \"0\" разошёлся с реальным сидом dedup_enabled=\"1\" в DEFAULT_SETTINGS — сейчас мёртвый код, ловушка на будущее" },
    { "ticket": "10", "axis": "spec", "file": "panel/main.py, userbot/client.py, userbot/main.py, panel/sources.py (докстринги)",
      "note": "остаточные упоминания setup.py в комментариях/докстрингах (не в пользовательском тексте бота — тот уже поправлен)" },
    { "ticket": "P1", "axis": "craft", "file": "panel/sources.py, panel/stats.py (import SESSION_DEAD_TEXT)",
      "note": "panel тянет весь worker (транзитивно userbot.deliver/client, worker.ratelimit) ради одной строки — общий текст логичнее было бы держать в общем месте (store/keyboards)" },
    { "ticket": "P1", "axis": "craft", "file": "panel/keywords.py + panel/keyboards.py (emoji-привязка, «❌ удалить»)",
      "note": "не покрыто тестом — test_keyboards.py не тестирует keyword_list_kb" },
    { "ticket": "P3", "axis": "spec", "file": "panel/stats.py format_history",
      "note": "get_entity для одного нечитаемого/удалённого чата упадёт на весь список истории из 50 записей, а не деградирует для одной строки — история раньше не имела сетевой зависимости вовсе, теперь имеет" }
  ],
  "reviewers": { "manifestSpec": "a6bd3fc4850da03ff", "craft": "a8bcf1b52452e96ee" },
  "blind": {
    "resolved": "все 9 расхождений закрыты тикетами 09 (экран настроек) и 10 (Docker-сборка, конфликт setup.py, TZ); оба независимо перепроверены двумя ревьюерами (реальный docker build + pip install -e, не пересказ отчёта исполнителя)",
    "drift": [
      { "req": "R26", "manifest": "done", "blind": "частично", "note": "monitor_all_dm — бэкенд готов, нет UI-переключателя" },
      { "req": "R31", "manifest": "done", "blind": "нет", "note": "card_template — рендер готов, нет UI-редактирования" },
      { "req": "R33", "manifest": "done", "blind": "частично", "note": "дедуп работает, окно/выключатель не в UI" },
      { "req": "R37", "manifest": "done", "blind": "частично", "note": "предохранитель работает, порог не в UI" },
      { "req": "R62", "manifest": "done", "blind": "частично", "note": "лимит работает, не настраивается в UI" },
      { "req": "R68", "manifest": "done", "blind": "частично", "note": "автоочистка работает, срок не в UI" },
      { "req": "R11", "manifest": "done", "blind": "нет", "note": "docker build падает — Dockerfile копирует не все пакеты до pip install ." },
      { "req": "R56/R60-соседний", "manifest": "done", "blind": "нет (сборка пакета)", "note": "pip install -e . падает — setup.py конфликтует с setuptools как legacy build script" },
      { "req": "R14", "manifest": "done", "blind": "частично", "note": "TZ пишется в .env мастером, но не читается в рантайме — settings.tz всегда дефолт" }
    ],
    "openQuestions": [
      "R17: собственный пример брифа «авто не ловит автора» не выполняется буквально (см. D01) — оставлено осознанно, без морфологии не развести с «ремонт»→«ремонтник»",
      "R53: диалог о догоне не показывается при паузе короче 60 секунд (порог не оговорён в брифе) — тихое возобновление вместо вопроса"
    ]
  }
}
